name: testing

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: outputcheck
      run: 'echo \'SANE=[[ "$(cat input)" == "$(cat output)" ]]\' >> "$GITHUB_ENV"'
    - name: output ok
      if: env.SANE == 1
      run: "happy"
    - name: fix
      if: env.SANE == 0
      run: 'cp input output'
