name: testing

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: outputcheck
      run: ./script.sh
    - name: output ok
      if: env.SANE == 'yes'
      run: 'happy'
    - name: fix
      if: env.SANE == 'no'
      run: |
        cp input output
        git config --global user.name "testboi[bot]"
        git config --global user.email "testboi[bot]@users.noreply.github.com"
        git add output
        git commit -m "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH"
        git push
        curl -f -L -X POST \
          -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/testing.yaml/dispatches \
          -d '{ "ref": "${{ github.head_ref }}"}'

