name: testing

# TODO: only run on prs, specifially dependabot prs
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    permissions:
      pull-requests: write
      contents: write
      issues: write
      statuses: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: outputcheck
      run: ./script.sh
    - name: output ok
      if: env.SANE == 'yes'
      run: echo 'happy'
    - name: fix
      if: env.SANE == 'no'
      run: |
        cp input output
        git config --global user.name "testboi[bot]"
        git config --global user.email "testboi[bot]@users.noreply.github.com"
        git add output
        git commit -m "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH"
        echo pushing
        git push
        echo close pr
        curl -v -f -L -X PATCH \
          -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} \
          -d '{"state":"closed"}'
        echo open pr
        curl -v -f -L -X PATCH \
          -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }} \
          -d '{"state":"open"}'
        echo "rerun me"
        exit 1

