name: testing

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: outputcheck
      run: '[[ "$(cat input)" == "$(cat output)" ]]'
